apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: build-model-storage
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    opendatahub.io/dashboard: "true"
  name: build-model-storage
  namespace: distance-prediction
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: 'true'
    opendatahub.io/image-display-name: Jupyter | Data Science | CPU | Python 3.12
    opendatahub.io/accelerator-name: ''
    openshift.io/description: ''
    openshift.io/display-name: build-model
    notebooks.opendatahub.io/last-image-version-git-commit-selection: d3137ca
    notebooks.opendatahub.io/last-image-selection: 'jupyter-datascience-cpu-py312-ubi9:2025.1'
    opendatahub.io/legacy-hardware-profile-name: small-notebooks-1bmle
    notebooks.opendatahub.io/last-size-selection: ''
    opendatahub.io/username: 'kube:admin'
    opendatahub.io/hardware-profile-name: ''
  name: build-model
  namespace: distance-prediction
  labels:
    app: build-model
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
    opendatahub.io/user: kube-3aadmin
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 8Gi
            requests:
              cpu: '1'
              memory: 8Gi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/distance-prediction/build-model/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: build-model
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/distance-prediction/build-model/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                                  --ServerApp.token=''
                                  --ServerApp.password=''
                                  --ServerApp.base_url=/notebook/distance-prediction/build-model
                                  --ServerApp.quit_button=False
                                  --ServerApp.tornado_settings={"user":"kube-3aadmin","hub_host":"https://rhods-dashboard-redhat-ods-applications{{ (lookup "v1" "Secret" "distance-prediction" "urls").data.BASE_URL | b64dec }}","hub_prefix":"/projects/distance-prediction"}
            - name: JUPYTER_IMAGE
              value: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/jupyter-datascience-cpu-py312-ubi9:2025.1'
            - name: PIP_CERT
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: REQUESTS_CA_BUNDLE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: SSL_CERT_FILE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: PIPELINES_SSL_SA_CERTS
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: GIT_SSL_CAINFO
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/app-root/src/
              name: build-model-storage
            - mountPath: /dev/shm
              name: shm
            - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
              name: trusted-ca
              readOnly: true
              subPath: ca-bundle.crt
            - mountPath: /opt/app-root/pipeline-runtimes/
              name: runtime-images
            - mountPath: /opt/app-root/runtimes
              name: elyra-dsp-details
          envFrom:
            - secretRef:
                name: urls
            - secretRef:
                name: postgres-creds
            - secretRef:
                name: my-token
          image: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/jupyter-datascience-cpu-py312-ubi9:2025.1'
          workingDir: /opt/app-root/src
        - resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: oauth-proxy
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8443
              name: oauth-proxy
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/oauth/client
              name: oauth-client
            - mountPath: /etc/oauth/config
              name: oauth-config
            - mountPath: /etc/tls/private
              name: tls-certificates
          image: 'registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4f8d66597feeb32bb18699326029f9a71a5aca4a57679d636b876377c2e95695'
          args:
            - '--provider=openshift'
            - '--https-address=:8443'
            - '--http-address='
            - '--openshift-service-account=build-model'
            - '--cookie-secret-file=/etc/oauth/config/cookie_secret'
            - '--cookie-expire=24h0m0s'
            - '--tls-cert=/etc/tls/private/tls.crt'
            - '--tls-key=/etc/tls/private/tls.key'
            - '--upstream=http://localhost:8888'
            - '--upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
            - '--email-domain=*'
            - '--skip-provider-button'
            - '--client-id=build-model-distance-prediction-oauth-client'
            - '--client-secret-file=/etc/oauth/client/secret'
            - '--scope=user:info user:check-access'
            - '--openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"build-model","namespace":"$(NAMESPACE)"}'
      enableServiceLinks: false
      serviceAccountName: build-model
      volumes:
        - name: build-model-storage
          persistentVolumeClaim:
            claimName: build-model-storage
        - emptyDir:
            medium: Memory
          name: shm
        - configMap:
            items:
              - key: ca-bundle.crt
                path: ca-bundle.crt
            name: workbench-trusted-ca-bundle
            optional: true
          name: trusted-ca
        - configMap:
            name: pipeline-runtime-images
            optional: true
          name: runtime-images
        - name: elyra-dsp-details
          secret:
            optional: true
            secretName: ds-pipeline-config
        - name: oauth-config
          secret:
            defaultMode: 420
            secretName: build-model-oauth-config
        - name: oauth-client
          secret:
            defaultMode: 420
            secretName: build-model-oauth-client
        - name: tls-certificates
          secret:
            defaultMode: 420
            secretName: build-model-tls