---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-data
    app.kubernetes.io/component: mysql-data
    app.kubernetes.io/instance: mysql-data
    app.kubernetes.io/name: mysql-data
    app.kubernetes.io/part-of: mysql-data
    component: mysql-data
  name: mysql-data
  namespace: distance-prediction
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: distance-prediction
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  ports:
    - name: mysql
      nodePort: 0
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: distance-prediction
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
      containers:
        - env:
            - name: MYSQL_USER
              value: "registryuser"
            - name: MYSQL_PASSWORD
              value: "registrypass"
            - name: MYSQL_DATABASE
              value: "modelregistry"
            - name: MYSQL_ROOT_PASSWORD
              value: "registrypass"
          args:
            - --datadir
            - /var/lib/mysql/datadir
            - --default-authentication-plugin=mysql_native_password
          image: "mysql:8.3.0"
          imagePullPolicy: IfNotPresent
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              cpu: "500m"
              memory: 1Gi
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
---
