{{- if .Values.enabled }}
{{- if .Values.route.enabled }}
---
# MinIO S3 API Route - External access to S3 API
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio-s3
  namespace: {{ .Values.namespace | default "distance-prediction" }}
  labels:
    app: minio
    app.kubernetes.io/component: s3-api
  annotations:
    {{- range $key, $val := .Values.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  host: minio-s3-{{ .Values.namespace | default "distance-prediction" }}.apps.{{ .Values.appsDomain | default "cluster.local" }}
  port:
    targetPort: s3  # MinIO S3 API on port 9000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: minio
    weight: 100
  wildcardPolicy: None
---
# MinIO Console Route - Web UI and console access
# Note: MinIO serves the console from the same S3 API endpoint
# Browser requests to /minio/ui/* are handled by MinIO itself
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio-console
  namespace: {{ .Values.namespace | default "distance-prediction" }}
  labels:
    app: minio
    app.kubernetes.io/component: console
  annotations:
    {{- range $key, $val := .Values.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  host: minio-console-{{ .Values.namespace | default "distance-prediction" }}.apps.{{ .Values.appsDomain | default "cluster.local" }}
  port:
    targetPort: s3  # Console is served from S3 API (port 9000)
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: minio
    weight: 100
  wildcardPolicy: None
{{- end }}
{{- end }}
