{{- if .Values.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-root-credentials
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $val := .Values.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
type: Opaque
stringData:
  rootUser: {{ .Values.auth.rootUser | quote }}
  rootPassword: {{ .Values.auth.rootPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-connection-pipeline-artifacts
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.auth.rootUser | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.auth.rootPassword | quote }}
{{- end }}


