{{- if .Values.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $val := .Values.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.database.user | quote }}
  MYSQL_DATABASE: {{ .Values.database.name | quote }}
  # Passwords will be injected from Vault or values-secret.yaml
  MYSQL_PASSWORD: {{ .Values.database.password | default "registrypass" | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | default "registrypass" | quote }}
{{- end }}


