---
# PostgreSQL values for Automated Braking Pattern
enabled: true

namespace: distance-prediction

image:
  repository: registry.redhat.io/rhel9/postgresql-16
  tag: "9.6"
  pullPolicy: IfNotPresent

# Database configuration
database:
  name: distance
  user: distanceuser
  password: distancepass  # Change in production!
  schema: distance

# Table schema for training data
schema:
  table: approaching_vehicle
  columns:
    - image_id INTEGER
    - other_bottom DECIMAL
    - other_left DECIMAL
    - other_right DECIMAL
    - other_top DECIMAL
    - other_speed INTEGER
    - your_speed DECIMAL
    - brake_amount DECIMAL
    - event_timestamp TIMESTAMP
    - created TIMESTAMP

# Resource limits
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 1Gi

# Persistent storage
persistence:
  enabled: true
  size: 10Gi
  storageClass: ""  # Use default
  accessMode: ReadWriteOnce

# Service configuration
service:
  port: 5432
  type: ClusterIP
  name: postgresql

# Database initialization
initDB:
  enabled: true
  backoffLimit: 5

# Labels and annotations
labels:
  app: postgresql
  app.kubernetes.io/name: postgresql
  app.kubernetes.io/part-of: automated-braking
  app.kubernetes.io/component: database

annotations:
  argocd.argoproj.io/sync-wave: "0"  # Deploy early with MySQL


