{{- if .Values.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-distance-prediction
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $val := .Values.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
data:
  init.sql: |
    \c {{ .Values.database.name }}
    CREATE SCHEMA {{ .Values.database.schema }} AUTHORIZATION {{ .Values.database.user }};
    create table {{ .Values.database.schema }}.{{ .Values.schema.table }}
    (
        image_id                             INTEGER,
        other_bottom                         DECIMAL,
        other_left                           DECIMAL,
        other_right                          DECIMAL,
        other_top                            DECIMAL,
        other_speed                          INTEGER,
        your_speed                           DECIMAL,
        brake_amount                         DECIMAL,
        event_timestamp                      TIMESTAMP,
        created                              TIMESTAMP
    );
    ALTER DATABASE {{ .Values.database.name }} OWNER TO {{ .Values.database.user }};
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.database.name }} TO {{ .Values.database.user }};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA {{ .Values.database.schema }} TO {{ .Values.database.user }};
{{- end }}


