{{- if .Values.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $val := .Values.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  ports:
    - name: postgresql
      nodePort: 0
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    name: postgresql
  sessionAffinity: None
  type: {{ .Values.service.type }}
{{- end }}


